"""
STS2 Mod Development Knowledge Base
------------------------------------
Based on actual working examples and local documentation.
Used by Code Agent and Planner to avoid looking up basics from scratch.

Sources:
- E:/STS2mod/docs/ (local verified docs with real bugs & solutions)
- https://github.com/lamali292/sts2_example_mod
- https://github.com/Alchyr/BaseLib-StS2
- sts2_api_reference.md (decompiled from sts2.dll, ilspycmd v9.1.0)
"""
from __future__ import annotations

from pathlib import Path

from app.modules.knowledge.infra.sts2_docs_source import Sts2DocsKnowledgeSource

# Full path to the decompiled API reference (same directory as this file)
API_REF_PATH = Path(__file__).parent / "sts2_api_reference.md"

# BaseLib decompiled source — committed to repo, always available
# Generated by: ilspycmd BaseLib.dll --outputdir backend/agents/baselib_src/
BASELIB_SRC_PATH = Path(__file__).parent / "baselib_src" / "BaseLib.decompiled.cs"

_RESOURCE_DIR = Path(__file__).parent.parent / "app" / "modules" / "knowledge" / "resources" / "sts2"


def _load_api_reference() -> str:
    """Load the decompiled API reference markdown. Returns empty string if missing."""
    try:
        return API_REF_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def _load_resource_text(file_name: str) -> str:
    return (_RESOURCE_DIR / file_name).read_text(encoding="utf-8").strip() + "\n"


_COMMON_DOCS = _load_resource_text("common.md")
_CARD_DOCS = _load_resource_text("card.md")
_RELIC_DOCS = _load_resource_text("relic.md")
_POWER_DOCS = _load_resource_text("power.md")
_POTION_DOCS = _load_resource_text("potion.md")
_CHARACTER_DOCS = _load_resource_text("character.md")
_CUSTOM_CODE_DOCS = _load_resource_text("custom_code.md")
_PLANNER_HINTS = _load_resource_text("planner_hints.md")


# Maps asset_type → type-specific snippet
_TYPE_DOCS: dict[str, str] = {
    "card": _CARD_DOCS,
    "card_fullscreen": _CARD_DOCS,
    "relic": _RELIC_DOCS,
    "power": _POWER_DOCS,
    "potion": _POTION_DOCS,
    "character": _CHARACTER_DOCS,
    "custom_code": _CUSTOM_CODE_DOCS + "\n" + _POTION_DOCS + "\n" + _CHARACTER_DOCS,
}


def _get_docs_for_type_raw(asset_type: str) -> str:
    """
    Return the combined knowledge base for a specific asset type.
    Includes: common build/structure docs + type-specific API snippet.
    Does NOT include the full decompiled reference (too large for prompt injection).
    """
    type_specific = _TYPE_DOCS.get(asset_type, "")
    return _COMMON_DOCS + type_specific


def _get_planner_api_hints_raw() -> str:
    """Return the compact planner hints from the resource bundle."""
    return _PLANNER_HINTS


_KNOWLEDGE_SOURCE = Sts2DocsKnowledgeSource(
    docs_for_type=_get_docs_for_type_raw,
    planner_hints=_get_planner_api_hints_raw,
)


def get_docs_for_type(asset_type: str) -> str:
    return _KNOWLEDGE_SOURCE.load_context("asset", asset_type=asset_type)


def get_planner_api_hints() -> str:
    return _KNOWLEDGE_SOURCE.load_context("planner")


# Legacy export: full docs for all types combined (kept for compatibility).
# Prefer get_docs_for_type(asset_type) in new code.
STS2_MOD_DOCS = (
    _COMMON_DOCS
    + _CARD_DOCS
    + _RELIC_DOCS
    + _POWER_DOCS
    + _CUSTOM_CODE_DOCS
)
